import { pool } from '../../config/database';

export const consultarInformes = async (desde: string, hasta: string) => {
  const rango = [desde, hasta];
  const [financiero, diario, produccion, vigilantes, cajas, auditorias] = await Promise.all([
    pool.query(`SELECT COALESCE(SUM(p.valor_pagado),0)::int recaudo_total, COALESCE(SUM(p.valor_pagado) FILTER(WHERE p.medio_pago='Efectivo'),0)::int efectivo, COALESCE(SUM(p.valor_pagado) FILTER(WHERE p.medio_pago='Nequi'),0)::int nequi, COALESCE((SELECT SUM(faltante_caja) FROM caja WHERE estado='cerrada' AND fecha_hora_cierre >= $1 AND fecha_hora_cierre < $2),0)::int faltantes, COALESCE((SELECT SUM(sobrante_caja) FROM caja WHERE estado='cerrada' AND fecha_hora_cierre >= $1 AND fecha_hora_cierre < $2),0)::int sobrantes FROM pago p WHERE p.fecha_hora_pago >= $1 AND p.fecha_hora_pago < $2`, rango),
    pool.query(`SELECT fecha, SUM(recaudo)::int recaudo_total, SUM(efectivo)::int efectivo, SUM(nequi)::int nequi, SUM(faltante)::int faltantes, SUM(sobrante)::int sobrantes FROM (SELECT DATE(fecha_hora_pago) fecha, valor_pagado recaudo, CASE WHEN medio_pago='Efectivo' THEN valor_pagado ELSE 0 END efectivo, CASE WHEN medio_pago='Nequi' THEN valor_pagado ELSE 0 END nequi, 0 faltante, 0 sobrante FROM pago WHERE fecha_hora_pago >= $1 AND fecha_hora_pago < $2 UNION ALL SELECT DATE(fecha_hora_cierre),0,0,0,faltante_caja,sobrante_caja FROM caja WHERE estado='cerrada' AND fecha_hora_cierre >= $1 AND fecha_hora_cierre < $2) d GROUP BY fecha ORDER BY fecha`, rango),
    pool.query(`SELECT DATE(fecha_hora_entrada) fecha, COUNT(*) FILTER(WHERE tipo_vehiculo='Carro')::int carros, COUNT(*) FILTER(WHERE tipo_vehiculo='Moto')::int motos, COUNT(*) FILTER(WHERE tipo_vehiculo='Bicicleta')::int bicicletas, COUNT(*)::int total FROM servicio WHERE fecha_hora_entrada >= $1 AND fecha_hora_entrada < $2 GROUP BY fecha ORDER BY fecha`, rango),
    pool.query(`SELECT c.id_colaborador, c.nombre vigilante, COUNT(*)::int cajas_cerradas, COUNT(*) FILTER(WHERE x.faltante_caja>0)::int cajas_con_faltante, COALESCE(SUM(x.faltante_caja),0)::int total_faltantes, COUNT(*) FILTER(WHERE x.sobrante_caja>0)::int cajas_con_sobrante, COALESCE(SUM(x.sobrante_caja),0)::int total_sobrantes FROM caja x JOIN colaborador c ON c.id_colaborador=x.id_colaborador WHERE x.estado='cerrada' AND x.fecha_hora_cierre >= $1 AND x.fecha_hora_cierre < $2 GROUP BY c.id_colaborador,c.nombre ORDER BY c.nombre`, rango),
    pool.query(`SELECT DATE(x.fecha_hora_cierre) fecha,x.id_caja,c.nombre vigilante,x.turno,x.recaudo_total,x.total_efectivo,x.total_nequi,x.efectivo_real,x.faltante_caja,x.sobrante_caja,x.novedades FROM caja x JOIN colaborador c ON c.id_colaborador=x.id_colaborador WHERE x.estado='cerrada' AND x.fecha_hora_cierre >= $1 AND x.fecha_hora_cierre < $2 ORDER BY x.fecha_hora_cierre`, rango),
    pool.query(`SELECT a.fecha_hora,c.nombre auditor,a.carros_sistema,a.carros_fisico,a.carros_fisico-a.carros_sistema diferencia_carros,a.motos_sistema,a.motos_fisico,a.motos_fisico-a.motos_sistema diferencia_motos,a.bicicletas_sistema,a.bicicletas_fisico,a.bicicletas_fisico-a.bicicletas_sistema diferencia_bicicletas,a.observaciones FROM auditoria a JOIN colaborador c ON c.id_colaborador=a.id_administrador_auditor WHERE a.fecha_hora >= $1 AND a.fecha_hora < $2 ORDER BY a.fecha_hora DESC`, rango),
  ]);
  return { financiero: financiero.rows[0], diario: diario.rows, produccion: produccion.rows, vigilantes: vigilantes.rows, cajas: cajas.rows, auditorias: auditorias.rows };
};
